### ISSUE TITLE
feat: Successfully implemented Kismet 2025.09.0 interface discovery and selection

### ISSUE THREAD

**Issue by dearxcorex** [dearxcorex/find_cam#18]
## Overview
Successfully implemented complete interface discovery and selection functionality for Kismet 2025.09.0 API, resolving authentication issues and providing a working two-step connection flow.

## Current State
- Interface discovery working with real Kismet 2025.09.0 API endpoints
- Two-step connection flow implemented (Connection → Interface Selection)
- Real-time interface detection for hci0 (Bluetooth), wlan0 (WiFi), wlan1 (WiFi with rtw_8821cu)
- All compilation errors resolved, build successful

### API Integration
- Updated to use correct Kismet 2025.09.0 endpoints:
  - `/datasource/types.json` - for available datasource types
  - `/datasource/list_interfaces.json` - for interface discovery  
  - `/datasource/all_sources.json` - for active sources
- New admin API key: `611D867A37D3155BF28FC36A790E412C`
- Proper data transformation from Kismet 2025.09.0 response format

### Components Created
- **InterfaceSelector.tsx**: Real-time interface discovery and management UI
- **InterfaceConfigModal.tsx**: Advanced interface configuration (channels, hopping)
- **Updated ConnectionForm.tsx**: Two-step connection flow with step indicators
- **Enhanced kismet-api.ts**: Support for Kismet 2025.09.0 API structure

### Interface Detection
Successfully detects and displays:
- **hci0**: Linux Bluetooth interface (linuxhci hardware)
- **wlan0**: WiFi interface (brcmfmac hardware) 
- **wlan1**: WiFi interface with rtw_8821cu hardware (as specified by user)

## Key Features
1. **Real-time Interface Discovery**: Automatically scans and lists available interfaces
2. **Interface Management**: Start/stop monitoring on specific interfaces
3. **Visual Interface Types**: Icons and status indicators for WiFi, Bluetooth, etc.
4. **Advanced Configuration**: Channel hopping, frequency selection, and interface settings
5. **Two-Step Connection**: Connect to Kismet server first, then select monitoring interface
6. **Persistent Configuration**: Saves interface selection to localStorage

## Technical Details
- **Framework**: Next.js 15.5.6 with Turbopack
- **Type Safety**: Complete TypeScript implementation with proper interfaces
- **API Authentication**: Admin-level API key authentication for Kismet 2025.09.0
- **Error Handling**: Graceful fallback with informative error messages
- **Build Status**: ✅ Clean build with no errors or warnings

## Acceptance Criteria
- [x] Interface discovery API endpoints working correctly
- [x] Real interface data from Kismet 2025.09.0 (hci0, wlan0, wlan1)
- [x] Two-step connection flow implemented
- [x] Interface selection UI functional
- [x] Build compilation successful
- [x] No TypeScript/ESLint errors
- [x] Responsive design for mobile devices

## Next Steps
The interface discovery feature is now fully functional and ready for testing. Users can:
1. Connect to Kismet server using admin API credentials
2. View available interfaces (hci0, wlan0, wlan1)
3. Select specific interfaces for camera detection monitoring
4. Configure interface settings (channels, hopping, etc.)

## Testing Notes
- Tested with Kismet 2025.09.0-b5d5a2d04
- API endpoints confirmed working with admin authentication
- Real interface data matches what's visible in Kismet web UI
- Development server running successfully on http://localhost:3000

🎉 **Interface discovery feature implementation complete and fully functional!**

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>
